ALTER TABLE `battleground_template`
DROP COLUMN `MinPlayersPerTeam`,
DROP COLUMN `MaxPlayersPerTeam`,
DROP COLUMN `MinLvl`,
DROP COLUMN `MaxLvl`,
DROP COLUMN `AllianceStartO`,
DROP COLUMN `HordeStartO`,
DROP COLUMN `StartMaxDist`,
DROP COLUMN `holiday`;
