CREATE TABLE `garr_follower_level_xp`
( `ID` INT(10) UNSIGNED NOT NULL DEFAULT 0,
`Level` INT(10) UNSIGNED NOT NULL DEFAULT 0,
`NextLevelXP` INT(10) UNSIGNED NOT NULL DEFAULT 0,
`Unknown` INT(10) UNSIGNED NOT NULL DEFAULT 0,
PRIMARY KEY (`ID`) )
ENGINE=MYISAM CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `garr_follower_quality`
( `ID` INT(10) UNSIGNED NOT NULL DEFAULT 0,
`Quality` INT(10) UNSIGNED NOT NULL DEFAULT 0, 
`NextQualityXP` INT(10) UNSIGNED NOT NULL DEFAULT 0, 
`Unknown` INT(10) UNSIGNED NOT NULL DEFAULT 0, 
PRIMARY KEY (`ID`) ) 
ENGINE=MYISAM CHARSET=utf8 COLLATE=utf8_general_ci;