ALTER TABLE `gameobject` ADD `AiID` INT(11) NOT NULL DEFAULT '0' AFTER `animprogress`;

ALTER TABLE `creature` 
ADD `AiID` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `dynamicflags`, 
ADD `MovementID` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `AiID`, 
ADD `MeleeID` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `MovementID`;